apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-with-annotations-and-labels
  namespace: kube-auth
  annotations:
    app.mintel.com/dex-k8s-ingress-watcher-client-id: cm-kube-auth
    app.mintel.com/dex-k8s-ingress-watcher-redirect-uri: https://cm.kube-auth.svc.cluster.local/oauth/callback
    app.mintel.com/dex-k8s-ingress-watcher-secret: cm-kube-auth
  labels:
    app.mintel.com/dex-k8s-ingress-watcher: enabled
