apiVersion: v1
kind: Secret
metadata:
  name: secret-with-annotations-and-labels
  namespace: default
  annotations:
    app.mintel.com/dex-k8s-ingress-watcher-client-id: secret-default
    app.mintel.com/dex-k8s-ingress-watcher-redirect-uri: https://secret.default.svc.cluster.local/oauth/callback
    app.mintel.com/dex-k8s-ingress-watcher-secret: secret-default
  labels:
    app.mintel.com/dex-k8s-ingress-watcher: enabled

