apiVersion: v1
kind: Secret
metadata:
  name: secret-with-annotations-and-labels
  namespace: kube-auth
  annotations:
    mintel.com/dex-k8s-ingress-watcher-client-id: secret-kube-auth
    mintel.com/dex-k8s-ingress-watcher-redirect-uri: https://secret.kube-auth.svc.cluster.local/oauth/callback
    mintel.com/dex-k8s-ingress-watcher-secret: secret-kube-auth
  labels:
    mintel.com/dex-k8s-ingress-watcher: enabled

